#include <stdio.h>
#include <stdlib.h>
#include "ocr.h"

int main()
{
  FILE *f = fopen("test-ocr-types.F90", "w");
  
  if (f == NULL)
    {
      printf("Error openings test-ocr-types.F90\n");
      exit(1);
    }
  
  fprintf(f, "!\n");
  fprintf(f, "! This file is generated by create-ocr-types.c\n");
  fprintf(f, "!\n\n");
  fprintf(f, "module test_ocr_types\n");
  fprintf(f, "use ISO_C_BINDING\n\n");

  
  fprintf(f, "integer(C_INT16_T), parameter :: DB_PROP_NONE = %i\n", 
	  DB_PROP_NONE);
  fprintf(f, "integer(C_INT16_T), parameter :: DB_PROP_NO_ACQUIRE = %i\n", 
	  DB_PROP_NO_ACQUIRE);
  fprintf(f, "integer(C_INT16_T), parameter :: DB_PROP_SINGLE_ASSIGNMENT = %i\n", 
	  DB_PROP_SINGLE_ASSIGNMENT);
  fprintf(f, "integer(C_INT16_T), parameter :: DB_PROP_NO_HINT = %i\n", 
	  DB_PROP_NO_HINT);


  fprintf(f, "integer(C_INT32_T), parameter :: EDT_PARAM_UNK = %i\n", 
	  EDT_PARAM_UNK);
  fprintf(f, "integer(C_INT32_T), parameter :: EDT_PARAM_DEF = %i\n", 
	  EDT_PARAM_DEF);
  fprintf(f, "integer(C_INT16_T), parameter :: EDT_PROP_NONE = %i\n", 
	  EDT_PROP_NONE);
  fprintf(f, "integer(C_INT16_T), parameter :: EDT_PROP_FINISH = %i\n", 
	  EDT_PROP_FINISH);
  fprintf(f, "integer(C_INT16_T), parameter :: EDT_PROP_NO_HINT = %i\n", 
	  EDT_PROP_NO_HINT);

  fprintf(f, "integer(C_INT16_T), parameter :: EVT_PROP_NONE = %i\n", 
	  EVT_PROP_NONE);
  fprintf(f, "integer(C_INT16_T), parameter :: EVT_PROP_TAKES_ARG = %i\n", 
	  EVT_PROP_TAKES_ARG);

  fprintf(f, "integer(C_INT16_T), parameter :: GUID_PROP_NONE = %i\n", 
	  GUID_PROP_NONE);
  fprintf(f, "integer(C_INT16_T), parameter :: GUID_PROP_IS_LABELED = %i\n", 
	  GUID_PROP_IS_LABELED);
  fprintf(f, "integer(C_INT16_T), parameter :: GUID_PROP_CHECK = %i\n", 
	  GUID_PROP_CHECK);
  fprintf(f, "integer(C_INT16_T), parameter :: GUID_PROP_BLOCK = %i\n", 
	  GUID_PROP_BLOCK);

  fprintf(f, "integer(C_INT16_T), parameter :: LEGACY_PROP_NONE = %i\n", 
	  LEGACY_PROP_NONE);
  fprintf(f, "integer(C_INT16_T), parameter :: LEGACY_PROP_WAIT_FOR_CREATE = %i\n", 
	  LEGACY_PROP_WAIT_FOR_CREATE);
  fprintf(f, "integer(C_INT64_t), parameter :: C_NULL = %i\n", 
	  0);
  
  fprintf(f, "integer(C_INT32_T), parameter :: NO_ALLOC = %i\n", 
	  NO_ALLOC);

  fprintf(f, "\nend module test_ocr_types\n");

  return 0;
}
