#include <stdio.h>
#include <stdlib.h>
#include "ocr.h"


void createTypeSizeHeader();
void createOcrTypes();

int main()
{
  createTypeSizeHeader();
  createOcrTypes();

  return 0;
}

void createOcrTypes()
{
  FILE *f = fopen("ocr-types.F90", "w");
  
  if (f == NULL)
    {
      printf("Error openings ocr-types.F90\n");
      exit(1);
    }
  
  fprintf(f, "!\n");
  fprintf(f, "! This file is generated by create-ocr-types.c\n");
  fprintf(f, "!\n\n");
  fprintf(f, "module ocr_types\n");
  fprintf(f, "use ISO_C_BINDING\n");
  fprintf(f, "implicit none\n");
  fprintf(f, "include 'ocr-type-size.h'\n\n");

  fprintf(f, "type, bind(C) :: ocrEdtDep_t\n");
  fprintf(f, "  integer(C_INTPTR_T) :: guid\n");
  fprintf(f, "  type(c_ptr) :: ptr\n");
  fprintf(f, "end type ocrEdtDep_t\n\n");

  fprintf(f, "type, bind(C) :: ocrEdt_t\n");
  fprintf(f, "  type(C_FUNPTR) :: ptr\n");
  fprintf(f, "end type ocrEdt_t\n\n");
  
  fprintf(f, "integer, parameter :: i32 = C_INT32_T\n");
  fprintf(f, "integer, parameter :: i64 = C_INT64_T\n\n");

  fprintf(f, "integer(C_INTPTR_T), bind(c, name=\"OFP_NULL_DEPV\"  ) :: NULL_DEPV(1)      = [-1]\n");
  fprintf(f, "integer(C_INT64_T),  bind(c, name=\"OFP_NULL_PARAMV\") :: NULL_PARAMV(1)    = [-1]\n");
  fprintf(f, "integer(C_INTPTR_T), bind(C, name=\"GUID_NULL_PTR\"  ) :: GUID_NULL_PTR(1)  = [-1]\n");
  fprintf(f, "integer(C_INT64_T),  bind(C, name=\"INT64_NULL_PTR\" ) :: INT64_NULL_PTR(1) = [-1]\n\n");

  fprintf(f, "integer(C_INTPTR_T), parameter :: NULL_GUID = 0\n");
  /* fprintf(f, "integer(C_INTPTR_T), dimension(1), parameter :: C_NULL_ARRAY = %i\n", 0); */
  fprintf(f, "integer(C_INT64_T), parameter :: C_NULL = %i\n", 
	  0);
  fprintf(f, "integer(C_INT32_T), parameter :: NO_ALLOC = %i\n\n", 
	  NO_ALLOC);
  

  ocrDbAccessMode_t dbaccess = DB_MODE_NULL;
  fprintf(f, "integer(C_INT32_T), parameter :: DB_MODE_NULL = %i\n",
	  dbaccess);
  dbaccess = DB_MODE_CONST;
  fprintf(f, "integer(C_INT32_T), parameter :: DB_MODE_CONST = %i\n",
	  dbaccess);
  dbaccess = DB_MODE_RW;
  fprintf(f, "integer(C_INT32_T), parameter :: DB_MODE_RW = %i\n",
	  dbaccess);
  dbaccess = DB_MODE_EW;
  fprintf(f, "integer(C_INT32_T), parameter :: DB_MODE_EW = %i\n",
	  dbaccess);
  dbaccess = DB_MODE_RO;
  fprintf(f, "integer(C_INT32_T), parameter :: DB_MODE_RO = %i\n",
	  dbaccess);


  fprintf(f, "integer(C_INT32_T), parameter :: OCR_EVENT_ONCE_T = %i\n",
	  OCR_EVENT_ONCE_T);
  fprintf(f, "integer(C_INT32_T), parameter :: OCR_EVENT_IDEM_T = %i\n",
	  OCR_EVENT_IDEM_T);
  fprintf(f, "integer(C_INT32_T), parameter :: OCR_EVENT_STICKY_T = %i\n",
	  OCR_EVENT_STICKY_T);
  fprintf(f, "integer(C_INT32_T), parameter :: OCR_EVENT_LATCH_T = %i\n",
	  OCR_EVENT_LATCH_T);
  
  fprintf(f, "integer(C_INT16_T), parameter :: DB_PROP_NONE = %i\n", 
	  DB_PROP_NONE);
  fprintf(f, "integer(C_INT16_T), parameter :: DB_PROP_NO_ACQUIRE = %i\n", 
	  DB_PROP_NO_ACQUIRE);
  fprintf(f, "integer(C_INT16_T), parameter :: DB_PROP_SINGLE_ASSIGNMENT = %i\n", 
	  DB_PROP_SINGLE_ASSIGNMENT);
  fprintf(f, "integer(C_INT16_T), parameter :: DB_PROP_NO_HINT = %i\n", 
	  DB_PROP_NO_HINT);


  fprintf(f, "integer(C_INT32_T), parameter :: EDT_PARAM_UNK = %i\n", 
	  EDT_PARAM_UNK);
  fprintf(f, "integer(C_INT32_T), parameter :: EDT_PARAM_DEF = %i\n", 
	  EDT_PARAM_DEF);
  fprintf(f, "integer(C_INT16_T), parameter :: EDT_PROP_NONE = %i\n", 
	  EDT_PROP_NONE);
  fprintf(f, "integer(C_INT16_T), parameter :: EDT_PROP_FINISH = %i\n", 
	  EDT_PROP_FINISH);
  fprintf(f, "integer(C_INT16_T), parameter :: EDT_PROP_NO_HINT = %i\n", 
	  EDT_PROP_NO_HINT);

  fprintf(f, "integer(C_INT16_T), parameter :: EVT_PROP_NONE = %i\n", 
	  EVT_PROP_NONE);
  fprintf(f, "integer(C_INT16_T), parameter :: EVT_PROP_TAKES_ARG = %i\n", 
	  EVT_PROP_TAKES_ARG);

  fprintf(f, "integer(C_INT16_T), parameter :: GUID_PROP_NONE = %i\n", 
	  GUID_PROP_NONE);
  fprintf(f, "integer(C_INT16_T), parameter :: GUID_PROP_IS_LABELED = %i\n", 
	  GUID_PROP_IS_LABELED);
  fprintf(f, "integer(C_INT16_T), parameter :: GUID_PROP_CHECK = %i\n", 
	  GUID_PROP_CHECK);
  fprintf(f, "integer(C_INT16_T), parameter :: GUID_PROP_BLOCK = %i\n", 
	  GUID_PROP_BLOCK);

  fprintf(f, "integer(C_INT16_T), parameter :: LEGACY_PROP_NONE = %i\n", 
	  LEGACY_PROP_NONE);
  fprintf(f, "integer(C_INT16_T), parameter :: LEGACY_PROP_WAIT_FOR_CREATE = %i\n", 
	  LEGACY_PROP_WAIT_FOR_CREATE);

  fprintf(f, "\nend module ocr_types\n");

  return;
}

void createTypeSizeHeader()
{
  FILE *f = fopen("ocr-type-size.h", "w");

  if (f == NULL)
    {
      printf("Error openings ocr-type-size.h\n");
      exit(1);
    }

  fprintf(f, "!\n");
  fprintf(f, "! This file is generated by create-ocr-type-size.c\n");
  fprintf(f, "!\n\n");

  fprintf(f, "integer, parameter :: LEN_OCRGUID_T = %ld\n",
          sizeof(ocrGuid_t));
  fprintf(f, "integer, parameter :: LEN_OCREDTDEP_T = %ld\n",
          sizeof(ocrEdtDep_t));
  fprintf(f, "integer, parameter :: LEN_S64 = %ld\n",
          sizeof(int64_t));
  fprintf(f, "integer, parameter :: LEN_S32 = %ld\n",
          sizeof(int32_t));
  fprintf(f, "integer, parameter :: LEN_S8 = %ld\n",
          sizeof(int8_t));

  return;
}

