!
! This file is generated by create-ocr-type-size.c
!

integer, parameter :: LEN_OCRGUID_T = 8
integer, parameter :: LEN_OCREDTDEP_T = 16
integer, parameter :: LEN_S64 = 8
integer, parameter :: LEN_S32 = 4
integer, parameter :: LEN_S8 = 1
