!
! This file is generated by create-ocr-types.c
!

module test_ocr_types
use ISO_C_BINDING

integer(C_INT16_T), parameter :: DB_PROP_NONE = 0
integer(C_INT16_T), parameter :: DB_PROP_NO_ACQUIRE = 16
integer(C_INT16_T), parameter :: DB_PROP_SINGLE_ASSIGNMENT = 32
integer(C_INT16_T), parameter :: DB_PROP_NO_HINT = 64
integer(C_INT32_T), parameter :: EDT_PARAM_UNK = -1
integer(C_INT32_T), parameter :: EDT_PARAM_DEF = -2
integer(C_INT16_T), parameter :: EDT_PROP_NONE = 0
integer(C_INT16_T), parameter :: EDT_PROP_FINISH = 1
integer(C_INT16_T), parameter :: EDT_PROP_NO_HINT = 2
integer(C_INT16_T), parameter :: EVT_PROP_NONE = 0
integer(C_INT16_T), parameter :: EVT_PROP_TAKES_ARG = 1
integer(C_INT16_T), parameter :: GUID_PROP_NONE = 0
integer(C_INT16_T), parameter :: GUID_PROP_IS_LABELED = 256
integer(C_INT16_T), parameter :: GUID_PROP_CHECK = 768
integer(C_INT16_T), parameter :: GUID_PROP_BLOCK = 1280
integer(C_INT16_T), parameter :: LEGACY_PROP_NONE = 0
integer(C_INT16_T), parameter :: LEGACY_PROP_WAIT_FOR_CREATE = 1
integer(C_INT64_t), parameter :: C_NULL = 0
integer(C_INT), parameter :: NO_ALLOC = 0

end module test_ocr_types
