#include <stdio.h>
#include <stdlib.h>
#include "ocr.h"

int main()
{
  FILE *f = fopen("ocr-type-size.h", "w");
  
  if (f == NULL)
    {
      printf("Error openings ocr-type-size.h\n");
      exit(1);
    }
  
  fprintf(f, "!\n");
  fprintf(f, "! This file is generated by create-ocr-type-size.c\n");
  fprintf(f, "!\n\n");
    
  fprintf(f, "integer, parameter :: LEN_OCRGUID_T = %ld\n", 
	  sizeof(ocrGuid_t));
  fprintf(f, "integer, parameter :: LEN_OCREDTDEP_T = %ld\n",
	  sizeof(ocrEdtDep_t));
  fprintf(f, "integer, parameter :: LEN_S64 = %ld\n", 
	  sizeof(int64_t));
  fprintf(f, "integer, parameter :: LEN_S32 = %ld\n", 
	  sizeof(int32_t));
  fprintf(f, "integer, parameter :: LEN_S8 = %ld\n", 
	  sizeof(int8_t));

  return 0;
}
