#include <stdio.h>
#include <stdlib.h>
#include "ocr.h"

void createOcrTypes();

int main()
{
  createOcrTypes();

  return 0;
}

void createOcrTypes()
{
  FILE *f = fopen("ocr-types.F90", "w");
  
  if (f == NULL)
    {
      printf("Error openings ocr-types.F90\n");
      exit(1);
    }
  
  fprintf(f, "!\n");
  fprintf(f, "! This file is generated by create-ocr-types.c\n");
  fprintf(f, "!\n\n");

  fprintf(f, "module ocr_types\n");
  fprintf(f, "use ISO_C_BINDING\n");
  fprintf(f, "use ocr_fortran_types\n");
  fprintf(f, "implicit none\n");

  fprintf(f, "integer(u32), parameter :: NO_ALLOC = %i\n\n", 
	  NO_ALLOC);

  ocrDbAccessMode_t dbaccess = DB_MODE_NULL;
  fprintf(f, "integer(u32), parameter :: DB_MODE_NULL = %i\n",
	  dbaccess);
  dbaccess = DB_MODE_CONST;
  fprintf(f, "integer(u32), parameter :: DB_MODE_CONST = %i\n",
	  dbaccess);
  dbaccess = DB_MODE_RW;
  fprintf(f, "integer(u32), parameter :: DB_MODE_RW = %i\n",
	  dbaccess);
  dbaccess = DB_MODE_EW;
  fprintf(f, "integer(u32), parameter :: DB_MODE_EW = %i\n",
	  dbaccess);
  dbaccess = DB_MODE_RO;
  fprintf(f, "integer(u32), parameter :: DB_MODE_RO = %i\n",
	  dbaccess);


  fprintf(f, "integer(u32), parameter :: OCR_EVENT_ONCE_T = %i\n",
	  OCR_EVENT_ONCE_T);
  fprintf(f, "integer(u32), parameter :: OCR_EVENT_IDEM_T = %i\n",
	  OCR_EVENT_IDEM_T);
  fprintf(f, "integer(u32), parameter :: OCR_EVENT_STICKY_T = %i\n",
	  OCR_EVENT_STICKY_T);
  fprintf(f, "integer(u32), parameter :: OCR_EVENT_LATCH_T = %i\n",
	  OCR_EVENT_LATCH_T);
  
  fprintf(f, "integer(u16), parameter :: DB_PROP_NONE = %i\n", 
	  DB_PROP_NONE);
  fprintf(f, "integer(u16), parameter :: DB_PROP_NO_ACQUIRE = %i\n", 
	  DB_PROP_NO_ACQUIRE);
  fprintf(f, "integer(u16), parameter :: DB_PROP_SINGLE_ASSIGNMENT = %i\n", 
	  DB_PROP_SINGLE_ASSIGNMENT);
  fprintf(f, "integer(u16), parameter :: DB_PROP_NO_HINT = %i\n", 
	  DB_PROP_NO_HINT);


  fprintf(f, "integer(u32), parameter :: EDT_PARAM_UNK = %i\n", 
	  EDT_PARAM_UNK);
  fprintf(f, "integer(u32), parameter :: EDT_PARAM_DEF = %i\n", 
	  EDT_PARAM_DEF);
  fprintf(f, "integer(u16), parameter :: EDT_PROP_NONE = %i\n", 
	  EDT_PROP_NONE);
  fprintf(f, "integer(u16), parameter :: EDT_PROP_FINISH = %i\n", 
	  EDT_PROP_FINISH);
  fprintf(f, "integer(u16), parameter :: EDT_PROP_NO_HINT = %i\n", 
	  EDT_PROP_NO_HINT);

  fprintf(f, "integer(u16), parameter :: EVT_PROP_NONE = %i\n", 
	  EVT_PROP_NONE);
  fprintf(f, "integer(u16), parameter :: EVT_PROP_TAKES_ARG = %i\n", 
	  EVT_PROP_TAKES_ARG);

  fprintf(f, "integer(u16), parameter :: GUID_PROP_NONE = %i\n", 
	  GUID_PROP_NONE);
  fprintf(f, "integer(u16), parameter :: GUID_PROP_IS_LABELED = %i\n", 
	  GUID_PROP_IS_LABELED);
  fprintf(f, "integer(u16), parameter :: GUID_PROP_CHECK = %i\n", 
	  GUID_PROP_CHECK);
  fprintf(f, "integer(u16), parameter :: GUID_PROP_BLOCK = %i\n", 
	  GUID_PROP_BLOCK);

  fprintf(f, "integer(u16), parameter :: LEGACY_PROP_NONE = %i\n", 
	  LEGACY_PROP_NONE);
  fprintf(f, "integer(u16), parameter :: LEGACY_PROP_WAIT_FOR_CREATE = %i\n", 
	  LEGACY_PROP_WAIT_FOR_CREATE);

  fprintf(f, "\nend module ocr_types\n");

  return;
}
