!
! This file is generated by create-ocr-types.c
!

module ocr_types
use ISO_C_BINDING
implicit none
include 'ocr-type-size.h'

type, bind(C) :: ocrEdtDep_t
  integer(C_INTPTR_T) :: guid
  type(c_ptr) :: ptr
end type ocrEdtDep_t

type, bind(C) :: ocrEdt_t
  type(C_FUNPTR) :: ptr
end type ocrEdt_t

integer(C_INTPTR_T), parameter :: NULL_GUID = 0
integer(C_INT64_T), parameter :: C_NULL = 0
integer(C_INT32_T), parameter :: NO_ALLOC = 0

integer(C_INT32_T), parameter :: DB_MODE_NULL = 0
integer(C_INT32_T), parameter :: DB_MODE_CONST = 1
integer(C_INT32_T), parameter :: DB_MODE_RW = 2
integer(C_INT32_T), parameter :: DB_MODE_EW = 4
integer(C_INT32_T), parameter :: DB_MODE_RO = 8
integer(C_INT32_T), parameter :: OCR_EVENT_ONCE_T = 0
integer(C_INT32_T), parameter :: OCR_EVENT_IDEM_T = 1
integer(C_INT32_T), parameter :: OCR_EVENT_STICKY_T = 2
integer(C_INT32_T), parameter :: OCR_EVENT_LATCH_T = 3
integer(C_INT16_T), parameter :: DB_PROP_NONE = 0
integer(C_INT16_T), parameter :: DB_PROP_NO_ACQUIRE = 16
integer(C_INT16_T), parameter :: DB_PROP_SINGLE_ASSIGNMENT = 32
integer(C_INT16_T), parameter :: DB_PROP_NO_HINT = 64
integer(C_INT32_T), parameter :: EDT_PARAM_UNK = -1
integer(C_INT32_T), parameter :: EDT_PARAM_DEF = -2
integer(C_INT16_T), parameter :: EDT_PROP_NONE = 0
integer(C_INT16_T), parameter :: EDT_PROP_FINISH = 1
integer(C_INT16_T), parameter :: EDT_PROP_NO_HINT = 2
integer(C_INT16_T), parameter :: EVT_PROP_NONE = 0
integer(C_INT16_T), parameter :: EVT_PROP_TAKES_ARG = 1
integer(C_INT16_T), parameter :: GUID_PROP_NONE = 0
integer(C_INT16_T), parameter :: GUID_PROP_IS_LABELED = 256
integer(C_INT16_T), parameter :: GUID_PROP_CHECK = 768
integer(C_INT16_T), parameter :: GUID_PROP_BLOCK = 1280
integer(C_INT16_T), parameter :: LEGACY_PROP_NONE = 0
integer(C_INT16_T), parameter :: LEGACY_PROP_WAIT_FOR_CREATE = 1

end module ocr_types
