!
! This file is generated by create-ocr-types.c
!

module ocr_fortran_types
use ISO_C_BINDING
use ocr_types
implicit none

type, bind(C) :: dbParams_t
  integer(C_INT64_T) :: rank
  integer(C_INT64_T) :: size
  integer(ocrGuid_k) ::  evt_finalize_guid
end type dbParams_t

end module ocr_fortran_types

module ocr_fortran
use ISO_C_BINDING
implicit none

contains
  function getArgv_i64(ptr, str, err) result(np)
    ! integer(C_INTPTR_T), intent(IN) :: ptr
    type(C_PTR), intent(IN) :: ptr
    character(len=*) :: str
    logical, intent(OUT) :: err
    integer(C_INT64_T) :: np, start, end

    start = index(str, '-np')
    if (start .eq. 0) then
       np = 0
       return
    end if

    start = start + 2
    do while (str(start+1:start+1) .eq. ' ')
       start = start + 1
    end do

    end = start
    do while (str(end+1:end+1) .ne. ' ')
       end = end + 1
    end do

    read (str(start+1:end), '(I10)') np
    return
  end function getArgv_i64
  
  function spmd_create_finalize_edt(n) result(edt_finalize)
    integer(C_INT64_T), intent(IN) :: n
    integer(C_INTPTR_T) :: edt_finalize
    integer :: i

    ! ocrEdtCreate(
    
  end function spmd_create_finalize_edt

  function create_spmd_edt(i, size, addr, edt_finalize) result (evt_start)
    integer(C_INT64_T) :: i, size
    type(C_FUNPTR) :: addr
    integer(C_INTPTR_T) :: edt_finalize
    integer(C_INTPTR_T) :: evt_start
    
    
  end function create_spmd_edt

end module ocr_fortran
